name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pytest httpx
    - name: Run basic tests
      run: |
        python -c "import fastapi; print('FastAPI imported successfully')"
        echo "Basic tests passed"

  deploy-notification:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deployment notification
      run: |
        echo "Code pushed to main branch"
        echo "Vercel will automatically deploy the changes"
        echo "Visit: https://public-job-portal1.vercel.app"