name: Sync Naraiteo Jobs to Firebase

on:
  schedule:
    # 5분마다 실행 (GitHub Actions 최소 단위는 5분)
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 수동 실행 가능
  
jobs:
  sync-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Firebase credentials
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        echo "$FIREBASE_CREDENTIALS" > job-portal-c9d7f-firebase-adminsdk-fbsvc-b0f6caa11d.json
    
    - name: Check for new jobs and sync
      env:
        NARAITEO_API_KEY: ${{ secrets.NARAITEO_API_KEY }}
      run: |
        python sync_new_jobs.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f job-portal-c9d7f-firebase-adminsdk-fbsvc-b0f6caa11d.json